apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: juice-loosener
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: "http,https"
    traefik.ingress.kubernetes.io/preserve-host: "true"
spec:
  tls:
  - hosts:
    - juice.lskysd.ca
  rules:
  - host: juice.lskysd.ca
    http:
      paths:
      - backend:
          serviceName: juice-loosener
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: juice-loosener
  labels:
    app: juice-loosener
spec:
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  selector:
    app.kubernetes.io/name: multi-juicer
  ports:
   - name: http
     port: 80
     targetPort: 3000
     protocol: TCP