apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multi-juicer
  labels:
    app: multi-juicer
spec:
  rules:
  - host: "juice.lskysd.ca"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: multi-juicer
              port:
                number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: multi-juicer
  labels:
    app: multi-juicer
spec:
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  selector:
    app.kubernetes.io/name: multi-juicer
  ports:
   - name: http
     port: 80
     targetPort: 3000
     protocol: TCP
