apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-configmap
  labels:
    app: traefik
data:
  TRAEFIK_ENTRYPOINTS_PORT443: "true"
  TRAEFIK_ENTRYPOINTS_PORT443_ADDRESS: :443
  TRAEFIK_ENTRYPOINTS_PORT443_HTTP_TLS: "true"
  TRAEFIK_ENTRYPOINTS_PORT80: "true"
  TRAEFIK_ENTRYPOINTS_PORT80_ADDRESS: :80
  TRAEFIK_ENTRYPOINTS_PORT80_HTTP_REDIRECTIONS_ENTRYPOINT_TO: port443
  TRAEFIK_ENTRYPOINTS_PORT80_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME: https
  TRAEFIK_ENTRYPOINTS_PORT80_HTTP_REDIRECTIONS_ENTRYPOINT_PERMANENT: "true"
  TRAEFIK_SERVERSTRANSPORT_INSECURESKIPVERIFY: "true"
  TRAEFIK_PROVIDERS_FILE_DIRECTORY: /dynconf
  TRAEFIK_PROVIDERS_KUBERNETESINGRESS: "true"
  TRAEFIK_API: "true"
  TRAEFIK_API_DASHBOARD: "true"
  TRAEFIK_API_INSECURE: "true"
  TRAEFIK_API_DEBUG: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-dynconfig
data:
  ssl.yml: |
    tls:
      stores:
        default:
          defaultCertificate:
            certFile: /secrets/tls.crt
            keyFile: /secrets/tls.key
---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-secrets
  labels:
    app: traefik
type: Opaque
data:
  tls.crt:  < BASE64 ENCODED CERT GOES HERE >
  tls.key: < BASE64 ENCODED KEY GOES HERE >
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-dashboard
  labels:
    app: traefik
spec:
  rules:
  - host: "traefik-ctf.lskysd.ca"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: traefik-dashboard
              port:
                number: 80
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress-controller
  labels:
    app: traefik
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress-controller
  labels:
    app: traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.4
          envFrom:
            - configMapRef:
                name: traefik-configmap
          volumeMounts:
            - mountPath: /secrets
              name: traefik-ssl
            - mountPath: /dynconf
              name: traefik-dynconf
          ports:
            - name: web
              containerPort: 80
              hostPort: 80
            - name: https
              containerPort: 443
              hostPort: 443
            - name: dashboard
              containerPort: 8080
      volumes:
        - name: traefik-ssl
          secret:
            secretName: traefik-secrets
        - name: traefik-dynconf
          configMap:
            name: traefik-dynconfig

---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
spec:
  selector:
    app: traefik
  ports:
    - protocol: TCP
      port: 80
      name: web
      targetPort: 8080
